service: express-lambda-api

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1

  environment:
    MONGO_URL: ${env:MONGO_URL} 

functions:
  api:
    handler: server.handler
    events:
      - httpApi: "*"